### ISSUE TITLE
libPyGEL.so

### ISSUE THREAD

**Issue by LogWell** [janba/GEL#15]
Hi, when I install package via `pip install PyGEL3D` and run `from PyGEL3D import gel`, an error occurs: `cannot open shared object file: No such file or directory`.

So I build on Linux,  `PyGEL3D-0.0.20-py3-none-any.whl is not a supported wheel on this platform.` occurred after run  `sudo -H pip install dist/PyGEL3D-*.whl` .

However I got the `libPyGEL.so` and copy to `.../lib/python3.6/site-packages/PyGEL3D`, now it runs successfully!

I don't know why, just keep going~

**Comment by janba** [comment]
Are you sure running pip install is not sufficient? You should not have to manually copy the so file

**Comment by LogWell** [comment]
Ohhh, but there's only one line of command in [http://www2.compute.dtu.dk/projects/GEL/PyGEL/](url)?

**Comment by janba** [comment]
Sure, but there is also a link to the github page where you have more detailed installation instructions. However, yes, I need to specify that pip only works for Mac and Windows. I think it is better for the Linux crowd to build and install from source.

**Comment by Amytipple** [comment]
Hi @janba, Thanks very much for this great library.
Please would you spell out how to compile from source for linux (18.04) I am not too familiar with make files.
I am trying to run from within a docker and get the exact same error as @LogWell:
```/usr/local/lib/python3.6/dist-packages/PyGEL3D/libPyGEL.so: cannot open shared object file: No such file or directory```

I tried the following
```git clone https://github.com/janba/GEL.git
     cd GEL
     mkdir build; cd build; cmake ..; make -j8 ; cd ..```

I also tried
```mkdir build; cd build; cmake -Use_GLGraphics=OFF..; make -j8 ; cd ..```
I built a .whl file but that gives the same error.
Thanks

**Comment by dh81** [comment]
I got the same problem, but cannot copy the libPyGEL.so because I cannot find it.

**Comment by janba** [comment]
I think the problem for LogWell was related to the installed tools. maybe an old version of pip. As for the comment by dh81: Look in the build folder.
