### ISSUE TITLE
Signed_distance Aborted

### ISSUE THREAD

**Issue by Amytipple** [janba/GEL#18]
Hi,
Thanks for the great library.
While using signed distance I get the following error for some points but not all:
`d = dist.signed_distance(pt)`

`python: /tmp/GEL/src/GEL/Geometry/BoundingTree.cpp:186: float Geometry::BoundingTree<BoxType>::compute_signed_distance(const CGLA::Vec3f&, float) const [with BoxType = Geometry::AABox]: Assertion `(hr.get_sq_dist_min() < (q0_max + DIST_THRESH)) || (hl.get_sq_dist_min() < (q0_max + DIST_THRESH))' failed.`

Ubuntu 18.04
I'm not sure how to interpret this error message.  Please would you advise why some input points are invalid.
Thanks

**Comment by janba** [comment]
Hi

I think that your query point or possibly the geometry is somehow invalid. Cannot say what simply by knowing the assertion failed. Also on vacation and cannot promise to do much.

However, literally gel tells you that the greatest distance to anything in a parent node of the bounding box tree is not greater than the smallest distance to something in either child node. This is not logical so it is kind of a sanity check .... that fails ... something is not sane

/a

Sent from my iPhone

On 11 Jul 2019, at 00.00, Amytipple <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
Thanks for the great library.
While using signed distance I get the following error for some points but not all:
d = dist.signed_distance(pt)

python: /tmp/GEL/src/GEL/Geometry/BoundingTree.cpp:186: float Geometry::BoundingTree<BoxType>::compute_signed_distance(const CGLA::Vec3f&, float) const [with BoxType = Geometry::AABox]: Assertion (hr.get_sq_dist_min() < (q0_max + DIST_THRESH)) || (hl.get_sq_dist_min() < (q0_max + DIST_THRESH))' failed.`

Ubuntu 18.04
I'm not sure how to interpret this error message. Please would you advise why some input points are invalid.
Thanks

**Comment by Amytipple** [comment]
Thanks for the quick response @janba enjoy your holiday. I will check the geometry and mesh that is generated.
