### ISSUE TITLE
Issues with installation using pip

### ISSUE THREAD

**Issue by piyush-bagad** [janba/GEL#24]
I used `pip install PyGEL3D` to install the package. However, on using `from PyGEL3D import gel` is throws up an error:
```
/home/users/piyushb/anaconda3/envs/anthro/lib/python3.7/site-packages/PyGEL3D/libPyGEL.so: cannot open shared object file: No such file or directory
```
This file does not exist in the installed package folder. Can anyone please help?

**Comment by janba** [comment]
Right. It is not a pure Python package - it contains some binary libraries. These have only been compiled for Mac and Windows. It looks like you might be on Linux. Please try the recipe found here "Building with CMake":

https://github.com/janba/GEL/blob/master/README.md

**Comment by MATRIX4284** [comment]
It will not compile still here is the error i am getting as there is some overloading issue here:
../src/GEL/Geometry/bounding_sphere.cpp:110:50: error: call of overloaded ‘isnan(const double&)’ is ambiguous
         if(!(isnan(p[0])||isnan(p[1])||isnan(p[2])))
                                                  ^
In file included from ../src/GEL/Geometry/../CGLA/ArithVec.h:18:0,
                 from ../src/GEL/Geometry/../CGLA/ArithVecInt.h:14,
                 from ../src/GEL/Geometry/../CGLA/ArithVec3Int.h:14,
                 from ../src/GEL/Geometry/../CGLA/Vec3i.h:15,
                 from ../src/GEL/Geometry/../CGLA/BitMask.h:14,
                 from ../src/GEL/Geometry/../CGLA/CGLA.h:4,
                 from ../src/GEL/Geometry/bounding_sphere.h:15,
                 from ../src/GEL/Geometry/bounding_sphere.cpp:11:
../src/GEL/Geometry/../CGLA/CGLA-util.h:85:17: note: candidate: bool CGLA::isnan(double)
     inline bool isnan(double x) {
                 ^~~~~
In file included from /usr/include/c++/7/random:38:0,
                 from ../src/GEL/Geometry/bounding_sphere.cpp:10:
/usr/include/c++/7/cmath:631:3: note: candidate: constexpr bool std::isnan(long double)
   isnan(long double __x)
   ^~~~~
/usr/include/c++/7/cmath:626:3: note: candidate: constexpr bool std::isnan(double)
   isnan(double __x)
   ^~~~~
/usr/include/c++/7/cmath:618:3: note: candidate: constexpr bool std::isnan(float)
   isnan(float __x)
   ^~~~~
fabricate: 'gcc' exited with status 1
