### ISSUE TITLE
Feature Request: AMGraph number of edges

### ISSUE THREAD

**Issue by timfelle** [janba/GEL#34]
It would be very usefull to have the option to get the number of edges in the graph structure, there is such a variable for the number of nodes `G.no_nodes()`, it would be great with `G.no_edges()` as well.

**Comment by janba** [comment]
AMGraph now has no_edges as well as no_nodes. Note that these functions return the number of edges and nodes created, respectively - not the current number: it is possible to disconnect nodes in an AMGraph, but not to remove them. However, if we remove an edge by disconnecting the incident nodes, no_edges() is not reduced. Nor does removing a node from an AMGraph3D cause no_nodes() to go down. However, in an AMGraph3D we can call cleanup (or call the free function clean_graph on an AMGraph3D). The cleaned graph will report the right number of nodes as well as edges.
