### ISSUE TITLE
Type Compare Warnings

### ISSUE THREAD

**Issue by timfelle** [janba/GEL#36]
When compiling a program using the GEL Library a number signedness compare warnings arrise: 
- GEL/Geometry/KDTree.h:302
- GEL/Geometry/KDTree.h:313
- GEL/Geometry/KDTree.h:410
- GEL/Geometry/KDTree.h:423
- GEL/Geometry/KDTree.h:429
- GEL/Geometry/Graph.h:226

**Comment by janba** [comment]
I changed the use of signed to unsigned ints in a number of places in these two files
