### ISSUE TITLE
Geometry::AMGraph::valid_node Extension to NaN

### ISSUE THREAD

**Issue by timfelle** [janba/GEL#40]
Currently the `valid_node` function only checks if a vertex in the graph have an invalid `NodeID`. However if a node is removed from the graph through for example `remove_node()` the `NodeID` is not set invalid.  

Could the `valid_node` function be changed to also check if the position of the point is NaN?

**Comment by janba** [comment]
It is not a completely trivial issue. Right now a node is valid (`valid_node` returns true) simply if the id corresponds to a valid index, i.e. an index smaller than the number of nodes allocated in the vector of nodes. The same is true for `valid_edge`. If they also check whether the position is a valid position, we would have changed the semantics of the functions. Moreover, the two functions are in `AMGraph` but the positions are only defined in `AMGraph3D`. 

My sense is that we need two smallish changes.

1. Rename `valid_node` -> `valid_node_id` and `valid_edge` -> `valid_edge_id` 
2. Introduce a new function in `AMGraph3D` which first tests whether the node is valid and then whether the position is not a Nan. Calling this function `in_use` would be consistent with `HMesh` but not everybody loves that name. 

I think these two changes would achieve what you are looking for?

**Comment by timfelle** [comment]
Sure it looks alright, but what is your reason for not using the current name for the extended check?  
`valid_node_id` Checks for only the `NodeID`  
`valid_node` Checks the extended condition of having a valid position in 3D. This way we avoid the `in_use` name and the name still make sense.  

I do see that compatibility with the current code might be problematic in some uses of existing code from other users. But are we sure it is not already expected? I would not call a node with a NaN position valid in any context, but others might..?

**Comment by janba** [comment]
it might come down to taste whether `valid_node` is a good name. However, it is used right now - and I am a bit afraid of reusing it for something else while giving the old function a new name. For this reason, the solution of using `in_use` seems attractive - especially since it also agrees with `HMesh`.

**Comment by janba** [comment]
Changes now applied (pending push) and for AMGraph3D you can use the `in_use` function to check if a node is actually being used in the graph.

You make a good point that some might consider a node with NaN position valid. A better solution would be to have a special flag that indicates whether a node has been removed. However, for now `in_use(n)` returns true if 

1. 0 < n < size of node vector
2. position of n is not nan
3. n has incident edges
