### ISSUE TITLE
Missing function isnan

### ISSUE THREAD

**Issue by timfelle** [janba/GEL#41]
Latest commit to the master does not compile due to a missing function. 
This is the output from attempting a clean install from a newly cloned repository.
Error log entry:

    $ cmake .. -DUse_GLGraphics=off;
    -- The C compiler identification is GNU 9.3.0
    -- The CXX compiler identification is GNU 9.3.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /usr/local/lib/GEL/lib

    $ make
    Scanning dependencies of target GEL
    [  1%] Building CXX object CMakeFiles/GEL.dir/src/GEL/CGLA/ArithSqMat3x3Float.cpp.o
    [  2%] Building CXX object CMakeFiles/GEL.dir/src/GEL/CGLA/ArithSqMat4x4Float.cpp.o
    [  3%] Building CXX object CMakeFiles/GEL.dir/src/GEL/CGLA/ArithVec2Float.cpp.o
    [  5%] Building CXX object CMakeFiles/GEL.dir/src/GEL/CGLA/ArithVec3Float.cpp.o
    [  6%] Building CXX object CMakeFiles/GEL.dir/src/GEL/CGLA/Mat3x3d.cpp.o
    [  7%] Building CXX object CMakeFiles/GEL.dir/src/GEL/CGLA/Mat3x3f.cpp.o
    [  9%] Building CXX object CMakeFiles/GEL.dir/src/GEL/CGLA/Mat4x4d.cpp.o
    [ 10%] Building CXX object CMakeFiles/GEL.dir/src/GEL/CGLA/Mat4x4f.cpp.o
    [ 11%] Building CXX object CMakeFiles/GEL.dir/src/GEL/CGLA/TableTrigonometry.cpp.o
    [ 13%] Building CXX object CMakeFiles/GEL.dir/src/GEL/CGLA/Vec2i.cpp.o
    [ 14%] Building CXX object CMakeFiles/GEL.dir/src/GEL/CGLA/Vec3f.cpp.o
    [ 15%] Building CXX object CMakeFiles/GEL.dir/src/GEL/CGLA/Vec3i.cpp.o
    [ 17%] Building CXX object CMakeFiles/GEL.dir/src/GEL/CGLA/eigensolution.cpp.o
    [ 18%] Building CXX object CMakeFiles/GEL.dir/src/GEL/CGLA/gel_rand.cpp.o
    [ 19%] Building CXX object CMakeFiles/GEL.dir/src/GEL/CGLA/statistics.cpp.o
    [ 21%] Building CXX object CMakeFiles/GEL.dir/src/GEL/Geometry/AABox.cpp.o
    [ 22%] Building CXX object CMakeFiles/GEL.dir/src/GEL/Geometry/BBox.cpp.o
    [ 23%] Building CXX object CMakeFiles/GEL.dir/src/GEL/Geometry/BSPTree.cpp.o
    /usr/local/lib/GEL/src/GEL/Geometry/BSPTree.cpp: In member function ‘bool Geometry::BSPTree::intersect(Geometry::Ray&,                      const Geometry::ISectTri&, double) const’:
    /usr/local/lib/GEL/src/GEL/Geometry/BSPTree.cpp:642:41: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     642 |     ray.hit_object = (TriMesh*)isecttri.mesh_id;
            |                                         ^~~~~~~
    [ 25%] Building CXX object CMakeFiles/GEL.dir/src/GEL/Geometry/BoundingINode.cpp.o
    [ 26%] Building CXX object CMakeFiles/GEL.dir/src/GEL/Geometry/BoundingLNode.cpp.o
    [ 27%] Building CXX object CMakeFiles/GEL.dir/src/GEL/Geometry/BoundingNode.cpp.o
    [ 28%] Building CXX object CMakeFiles/GEL.dir/src/GEL/Geometry/BoundingTree.cpp.o
    [ 30%] Building CXX object CMakeFiles/GEL.dir/src/GEL/Geometry/GradientFilter.cpp.o
    [ 31%] Building CXX object CMakeFiles/GEL.dir/src/GEL/Geometry/Graph.cpp.o
    In file included from /usr/local/lib/GEL/src/GEL/Geometry/Graph.cpp:12:
    /usr/local/lib/GEL/src/GEL/Geometry/Graph.h: In member function ‘bool    Geometry::AMGraph3D::in_use(Geometry::AMGraph::NodeID) const’:
    /usr/local/lib/GEL/src/GEL/Geometry/Graph.h:204:16: error: ‘isnan’ was not declared in this scope
     204 |             if(isnan(pos[n][0]) && edge_map.empty())
            |                ^~~~~
    /usr/local/lib/GEL/src/GEL/Geometry/Graph.h:204:16: note: suggested alternatives:
    In file included from /usr/local/lib/GEL/src/GEL/Geometry/../CGLA/CGLA-util.h:18,
                 from /usr/local/lib/GEL/src/GEL/Geometry/../CGLA/ArithVec.h:18,
                 from /usr/local/lib/GEL/src/GEL/Geometry/../CGLA/ArithVecFloat.h:14,
                 from /usr/local/lib/GEL/src/GEL/Geometry/../CGLA/ArithVec3Float.h:15,
                 from /usr/local/lib/GEL/src/GEL/Geometry/../CGLA/Vec3d.h:14,
                 from /usr/local/lib/GEL/src/GEL/Geometry/Graph.h:18,
                 from /usr/local/lib/GEL/src/GEL/Geometry/Graph.cpp:12:
    /usr/include/c++/9/cmath:632:5: note:   ‘std::isnan’
     632 |     isnan(_Tp __x)
            |     ^~~~~
    In file included from /usr/local/lib/GEL/src/GEL/Geometry/../CGLA/ArithVec.h:18,
                 from /usr/local/lib/GEL/src/GEL/Geometry/../CGLA/ArithVecFloat.h:14,
                 from /usr/local/lib/GEL/src/GEL/Geometry/../CGLA/ArithVec3Float.h:15,
                 from /usr/local/lib/GEL/src/GEL/Geometry/../CGLA/Vec3d.h:14,
                 from /usr/local/lib/GEL/src/GEL/Geometry/Graph.h:18,
                 from /usr/local/lib/GEL/src/GEL/Geometry/Graph.cpp:12:
    /usr/local/lib/GEL/src/GEL/Geometry/../CGLA/CGLA-util.h:85:17: note:   ‘CGLA::isnan’
    85 |     inline bool isnan(double x) {
         |                 ^~~~~
    make[2]: *** [CMakeFiles/GEL.dir/build.make:381: CMakeFiles/GEL.dir/src/GEL/Geometry/Graph.cpp.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:124: CMakeFiles/GEL.dir/all] Error 2
    make: *** [Makefile:149: all] Error 2

**Comment by janba** [comment]
dang. namespace issue. fixed
