### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by timfelle** [janba/GEL#42]
The code does not compile with the following commands.

     cmake -DUse_GLGraphics=off ..
     make

The error message looks like:

    [ 78%] Building CXX object CMakeFiles/GEL.dir/src/GEL/HMesh/refine_edges.cpp.o
    In file included from /usr/include/c++/9/vector:60,
                 from /usr/local/lib/gel/src/GEL/HMesh/refine_edges.cpp:9:
    /usr/include/c++/9/bits/stl_algobase.h: In instantiation of ‘_OI std::__copy_move_a(_II, _II, _OI) [with bool _IsMove = false; _II = HMesh::IDIterator<HMesh::HalfEdge>; _OI = std::back_insert_iterator<std::vector<HMesh::ItemID<HMesh::HalfEdge> > >]’:
    /usr/include/c++/9/bits/stl_algobase.h:441:30:   required from ‘_OI std::__copy_move_a2(_II, _II, _OI) [with bool _IsMove = false; _II = HMesh::IDIterator<HMesh::HalfEdge>; _OI = std::back_insert_iterator<std::vector<HMesh::ItemID<HMesh::HalfEdge> > >]’
    /usr/include/c++/9/bits/stl_algobase.h:474:7:   required from ‘_OI std::copy(_II, _II, _OI) [with _II = HMesh::IDIterator<HMesh::HalfEdge>; _OI = std::back_insert_iterator<std::vector<HMesh::ItemID<HMesh::HalfEdge> > >]’
    /usr/local/lib/gel/src/GEL/HMesh/refine_edges.cpp:44:75:   required from here
    /usr/include/c++/9/bits/stl_algobase.h:395:57: error: no type named ‘value_type’ in ‘struct std::iterator_traits<HMesh::IDIterator<HMesh::HalfEdge> >’
      395 |       typedef typename iterator_traits<_II>::value_type _ValueTypeI;
             |                                                         ^~~~~~~~~~~
    /usr/include/c++/9/bits/stl_algobase.h:397:64: error: no type named ‘iterator_category’ in ‘struct std::iterator_traits<HMesh::IDIterator<HMesh::HalfEdge> >’
      397 |       typedef typename iterator_traits<_II>::iterator_category _Category;
             |                                                                ^~~~~~~~~
    /usr/include/c++/9/bits/stl_algobase.h:401:9: error: no type named ‘value_type’ in ‘struct std::iterator_traits<HMesh::IDIterator<HMesh::HalfEdge> >’
      398 |       const bool __simple = (__is_trivially_copyable(_ValueTypeI)
             |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      399 |         && __is_pointer<_II>::__value
             |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      400 |         && __is_pointer<_OI>::__value
             |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      401 |         && __are_same<_ValueTypeI, _ValueTypeO>::__value);
             |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/c++/9/bits/stl_algobase.h:404:30: error: no type named ‘iterator_category’ in ‘struct std::iterator_traits<HMesh::IDIterator<HMesh::HalfEdge> >’
      403 |       return std::__copy_move<_IsMove, __simple,
             |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      404 |          _Category>::__copy_m(__first, __last, __result);
             |          ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
    make[2]: *** [CMakeFiles/GEL.dir/build.make:830: CMakeFiles/GEL.dir/src/GEL/HMesh/refine_edges.cpp.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/GEL.dir/all] Error 2
    make: *** [Makefile:130: all] Error 2

**Comment by janba** [comment]
Right. It looks like I had to roll back some changes to the IDIterator class to make it compile on Linux, but it does compile on Linux now - at least for me: I'd be grateful if you try again.
