### ISSUE TITLE
ISO C++ warning

### ISSUE THREAD

**Issue by timfelle** [janba/GEL#43]
I now get a warning from the Delaunay_triangulation stating string constants cannot be converted to string pointers according to the ISO C++ standard.

    [ 31%] Building CXX object CMakeFiles/GEL.dir/src/GEL/HMesh/x3d_load.cpp.o
    /usr/local/lib/gel/src/GEL/HMesh/Delaunay_triangulate.cpp: In function ‘HMesh::Manifold HMesh::Delaunay_triangulate(const std::vector<CGLA::Vec3d>&, const CGLA::Vec3d&, const CGLA::Vec3d&)’:
    /usr/local/lib/gel/src/GEL/HMesh/Delaunay_triangulate.cpp:44:21: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
       44 |         triangulate("zBSQ", &pts_in, &tri_out, 0);
          |                     ^~~~~~

**Comment by janba** [comment]
Right. This was a small thing that I had ignored but it is fixed now. I also made sure that a few other warnings do not show up, and now the build is clean for me on Linux and MacOS.
