### ISSUE TITLE
Geometry expansion/erosion

### ISSUE THREAD

**Issue by SimonBiggs** [janba/GEL#59]
Hi @janba,

Thank you for this brilliant library :slightly_smiling_face:. I was wondering if there was plans on the roadmap to implement 3D geometry erosion or expansion algorithms? Unfortunately the buffer function in shapely doesn't work in 3D:

https://github.com/shapely/shapely/blob/main/FAQ.rst#i-used-buffer-on-a-geometry-with-z-coordinates-where-did-the-z-coordinates-go

Cheers,
Simon

**Comment by janba** [comment]
Hi Simon,

It is already quite feasible to do erosion and dilation via distance fields. If you look here:

https://people.compute.dtu.dk/janba/isocontouring.html

In the last example, the Stanford bunny is converted to a distance field and then polygonized. If you polygonize an isocontour with isovalue greater or smaller than zero, then it corresponds to a dilation or erosion, respectively.

I have not yet included hmesh.volumetric_isocontour in the master branch (and it is also not in the pip package) but if you download and compile the experimental branch you should be good to go.

Cheers
Andreas

On 27 Oct 2022, at 01.21, Simon Biggs ***@***.******@***.***>> wrote:



Hi @janba<https://github.com/janba>,

Thank you for this brilliant library 🙂. I was wondering if there was plans on the roadmap to implement 3D geometry erosion or expansion algorithms? Unfortunately the buffer function in shapely doesn't work in 3D:

https://github.com/shapely/shapely/blob/main/FAQ.rst#i-used-buffer-on-a-geometry-with-z-coordinates-where-did-the-z-coordinates-go

Cheers,
Simon

**Comment by SimonBiggs** [comment]
Oh! That is amazing! Thank you!

I will do.
