### ISSUE TITLE
High scale graph -> low scale skeleton

### ISSUE THREAD

**Issue by kdmarrett** [janba/GEL#63]
I've been struggling on usage of skeletonization for an academic research project, and I think someone with the intution of GEL can spot a solution quickly.

I have a high scale quad mesh with 169k points and am struggling to get a final skeleton with about 1000 skeletal nodes even when maxing out the parameters which increase coarseness. For example using local_separators with quality noise level .9999 I still get 112k final skeletal nodes. With multiscale_local_separators grow threshold 2 and quality threshold .9999 I still get over 100k nodes. Both of these strategies yield skeletons 2 orders of magnitude more than expected from the simple shape they represent.

I may have an issue in how I am inputting the quad mesh into the local separators algorithms. I start with a highly dense quad mesh with close by points. I add the points to the graph, then I traverse each quad in clockwise order and connect_nodes(a,b) in the same AMGraph3D, then I pass the resulting graph to the local separators.

Because the skeletons were so fine-grained and dense (>100k) I tried pre-coarsening my AMGraph3D before passing it to local_separators() like so:

```
uint desired_node_count = 1000;
auto msg = Geometry::multiscale_graph(g, desired_node_count, true);
g = msg.layers.back(); // get the coarsest (smallest) graph representation in the hierarchy
```
...but the output skeletons had this radial branching issue that looked like fig 9 in your arxiv:
![radial-branching](https://github.com/janba/GEL/assets/7285726/e16face1-3aab-42b2-b14f-0cc72aeefdc3)

Instead of putting the quad mesh directly into an AMGraph3D do you recommend, transforming it into a HMesh then coarsening the mesh with your functions before passing it into local_separators?

**Comment by janba** [comment]
Hi Karl,

It is discussed in the paper that you cannot compute the skeleton of a quad mesh, but I guess the documentation does not cover the issue.

It should not matter how the graph is generated, but you need to triangulate the mesh before converting it into a graph. Alternatively, you can just add one or both diagonals to your graph with your existing code. If you add both, the local separators will be slightly bigger, though, and the skeleton slightly coarser.

The reason is as follows: When the local separators are computed, you start from a vertex and then expand a front outwards. When the front breaks into several pieces we know that the vertices behind the front are a _local_ separator. Unfortunately, this happens right away in a quad mesh: each of the four neighbors of a vertex is its own connected component. Clearly, we could have fixed this with some sort of special case handling, but since you can triangulate it seemed unnecessary. Should have made it more explicit in the docs I guess.

**Comment by kdmarrett** [comment]
Right you do mention the quad issue more than once in the LS paper which is very helpful, the problem is with all 4 edges and 2 diagonals added a 146256 node graph generated directly from a quad mesh (shown below) yields a 146256 node skeleton even when the threshold is .9999 and the grow threshold is 2 with multiscale_local_separators().

This is how I transform the mesh into a graph:

```
 60 template <typename Poly>
 61 auto unroll_polygons(std::vector<Poly> polys, Geometry::AMGraph3D &g,
 62   | ¦ ┆ ┊ | ¦ ┆ ┊ | ¦unsigned int order) {
 63   // list all connections of the 0-indexed points
 64   rng::for_each(polys, [&](auto poly) {
 65   | for (unsigned int i = 0; i < order; ++i) {
 66   | ¦ auto a = poly[i];
 67   | ¦ auto b = poly[(i + 1) % order];
 68   | ¦ g.connect_nodes(a, b);
 69   | }
 70
 71   | // quads can not be directly skeletonized by the local separator approach
 72   | // so you must create connections along a diagonal
 73   | // do both diagonals for coarser final skeletons
 74   | if (order == 4) {
 75   | ¦ g.connect_nodes(poly[0], poly[2]);
 76   | ¦ g.connect_nodes(poly[1], poly[3]);
 77   | }
 78   });
 79 };
```

calling multiscale:

```
184   | ¦ ┆ uint grow_threshold =
185   | ¦ ┆ ┊ | 4; // 4 had lowest resolution, higher is finer granularity
186   | ¦ ┆ // multi-scale is faster and scales linearly with input graph size at the
187   | ¦ ┆ // cost of difficulty in choosing a grow threshold
188   | ¦ ┆ auto separators =
189   | ¦ ┆ ┊ | multiscale_local_separators(g, Geometry::SamplingType::Advanced,
190   | ¦ ┆ ┊ | ¦ ┆ ┊ | ¦ ┆ ┊ | ¦ ┆ ┊ | ¦ ┆ grow_threshold, .999);
192   | ¦ ┆ auto [component_graph, mapping] =
193   | ¦ ┆ ┊ | skeleton_from_node_set_vec(g, separators);
```
Do you think it is failing for another reason. Note that the mesh is generated from an SDF voxel grid and each point is only a voxel apart. Unless this looks fishy maybe my next step should be to transform it into a HMesh::Manifold, quad_simplify(), then pass it to local separators?

**Comment by kdmarrett** [comment]
I converted to Manifold again with triangles, then converted the manifold to graph and the local separators had a node count ~1000 thus fixing the issue for me, thank you for the feedback.

**Comment by janba** [comment]
One issue that I saw with your code is that you seemingly don't create the nodes, but this could happen outside what is shown. Another issue could be if the polygon's faces were not stitched - i.e. if geometrically identical points are for some reason different vertices. Whatever the reason, I am glad that you fixed it.
