### ISSUE TITLE
Convolutional Surfacing

### ISSUE THREAD

**Issue by kdmarrett** [janba/GEL#65]
Can you help me find which is the function you used to transform a graph into a mesh via convolutional surfacing, used in the original SIGGRAPH paper

**Comment by kdmarrett** [comment]
is it graph_to_FEQ?

**Comment by janba** [comment]
Yes. It has improved recently and is still work in progress, but you might want to look at the experimental2 branch. It works a bit differently in that branch. /Andreas
________________________________
