### ISSUE TITLE
Cannot add edges in the graph.

### ISSUE THREAD

**Issue by Philip035** [janba/GEL#71]
Hello!
I am trying to use this library to skeletonization a point cloud data, and I tried to define a graph and add edges, but it seems some errors.
Here is my code:
```
#include<iostream>
#include<cstdlib>
#include<GEL/Geometry/graph_util.h>
#include<GEL/Geometry/graph_io.h>
#include<GEL/Geometry/Graph.h>
#include<GEL/Geometry/graph_skeletonize.h>
#include<GEL/CGLA/CGLA.h>
#include<GEL/CGLA/ArithVec.h>
#include<GEL/CGLA/Vec3d.h>
#include<GEL/Util/Range.h>
using namespace std; // For input output
using namespace CGLA;
int main()
{
    Geometry::AMGraph3D graph;
    for (int i = 0;i < 100;++i)
    {
        Vec3d p0(double(i),double(i+1),double(i+2));
        graph.add_node(p0);
    }
    Geometry::AMGraph::EdgeID e  = graph.connect_nodes(1,2);
    return 0;
}
```
**_Error list_** repoted that "Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: static unsigned __int64 const Geometry::AMGraph::InvalidEdgeID" (?InvalidEdgeID@AMGraph@Geometry@@2_KB)	GEL_Demo	E:\Mycode\GEL_Demo\GEL_Demo\Source.obj	1	"

My compiler is **VS2019**, and environment is **Windows 10**.
In addition, if a reference code about skeletonizationing the point cloud can be given, that will be very nice.

**Comment by Philip035** [comment]
> Hello! I am trying to use this library to skeletonization a point cloud data, and I tried to define a graph and add edges, but it seems some errors. Here is my code:
> 
> ```
> #include<iostream>
> #include<cstdlib>
> #include<GEL/Geometry/graph_util.h>
> #include<GEL/Geometry/graph_io.h>
> #include<GEL/Geometry/Graph.h>
> #include<GEL/Geometry/graph_skeletonize.h>
> #include<GEL/CGLA/CGLA.h>
> #include<GEL/CGLA/ArithVec.h>
> #include<GEL/CGLA/Vec3d.h>
> #include<GEL/Util/Range.h>
> using namespace std; // For input output
> using namespace CGLA;
> int main()
> {
>     Geometry::AMGraph3D graph;
>     for (int i = 0;i < 100;++i)
>     {
>         Vec3d p0(double(i),double(i+1),double(i+2));
>         graph.add_node(p0);
>     }
>     Geometry::AMGraph::EdgeID e  = graph.connect_nodes(1,2);
>     return 0;
> }
> ```
> 
> **_Error list_** repoted that "Severity Code Description Project File Line Suppression State Error LNK2001 unresolved external symbol "public: static unsigned __int64 const Geometry::AMGraph::InvalidEdgeID" (?InvalidEdgeID@AMGraph@Geometry@@2_KB) GEL_Demo E:\Mycode\GEL_Demo\GEL_Demo\Source.obj 1 "
> 
> My compiler is **VS2019**, and environment is **Windows 10**. In addition, if a reference code about skeletonizationing the point cloud can be given, that will be very nice.

Oh, I have found where i am wrong. I set the library folder path falsely.
Meanwhile, I still want to get a reference code about the skeletonization, could you give more C++ API reference?

**Comment by janba** [comment]
I don't have too many resources for example making, but a good skeletonization example is a great idea, so here goes:
```
#include <GEL/Geometry/Graph.h>
#include <GEL/Geometry/graph_io.h>
#include <GEL/Geometry/graph_skeletonize.h>
#include <GEL/HMesh/skeleton_to_FEQ.h>
#include <GEL/HMesh/HMesh.h>

using namespace Geometry;
using namespace HMesh;
using namespace std;

int main(int argc, char** argv) {
    // Load the points, use a kD tree to connect nearest points.
    // First argument is radius, second is max number of neighbors.
    AMGraph3D g = graph_from_points("./data/armadillo.pts", 7.5, 15);
    
    // Now compute the separators for the skeletonization
    NodeSetVec separators = multiscale_local_separators(g);
    
    // Compute the skeleton from the separators.
    AMGraph3D s = skeleton_from_node_set_vec(g, separators).first;
    
    // And reconstruct a mesh from the skeleton.
    vector<double> radii(s.no_nodes());
    for (auto n: s.node_ids())
        radii[n] = 3;
    Manifold m = graph_to_FEQ(s, radii);
    obj_save("data/armadillo_recon.obj", m);
    return 0;
}
```
I will add this to the code base also in the foreseeable future...
